# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :disksubsystem => {
        :box_name => "generic/debian11",
        :disks => {
            :sata1 => {
                :dfile => './sata1.vdi',
                :size => 20480,
                :port => 1
            },
            :sata2 => {
                :dfile => './sata2.vdi',
                :size => 20480,
                :port => 2
            }
        }
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          # Отключить автообновление virtualbox addons, для данного задания они не нужны
          # если плагин vbguest не установлен - необходимо закомментировать
          box.vbguest.auto_update = false

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
            needsController = false
            boxconfig[:disks].each do |dname, dconf|
                unless File.exist?(dconf[:dfile])
                    vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Standard', '--size', dconf[:size]]
                    needsController =  true
                end
            end
            if needsController == true
                # for virtualbox 7 choose SAS Controller
                vb.customize ["storagectl", :id, "--name", "SAS Controller", "--add", "sas" ]
                boxconfig[:disks].each do |dname, dconf|
                    vb.customize ['storageattach', :id,  '--storagectl', 'SAS Controller', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                end
            end
          end


        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            apt-get update
            apt-get install -y mdadm smartmontools hdparm gdisk lshw parted dump
        SHELL

      end
  end
end
